### ISSUE TITLE
考虑增加处理 res 的切面？

### ISSUE THREAD

**Issue by gyh9457** [gem-mine/request#21]
目前，一个成功的请求，在 `verify` 之后的切面里，拿到的都是 res.data。
这对于一般的请求是够用的，但对于一些特殊的请求，是不够的。
比如一个下载文件的请求，后端把文件名放在 header `Content-Disposition`，这时候必须拿到完整的相应数据。

一个变通的方法是在 `verify` 里面处理
```js
  request.get('xxx', {
    verify: (res) => {
      const { status, headers } = res
      console.log(headers)
      return status >= 200 && status < 300;
    }
  })
    .then(data => {
      console.log(data)
    })
```

但这显然和 `verify` 的初衷不符。

**Comment by caolvchong** [comment]
给所有有返回值的 callback 的函数都添加一个参数 response

![image](https://user-images.githubusercontent.com/1551325/102049985-e5c79200-3e1c-11eb-9fcc-d49eaf706f21.png)

pr：https://github.com/gem-mine/request/pull/23
